import type { Site } from './types';

const rand = (len = 12) => Math.random().toString(36).slice(2, 2 + len);

export const SITES: Site[] = [
  // ── finance (rare → survey hard) ─────────────────────────────────
  {
    id: 'secure-bank',
    name: 'SecureBank',
    category: 'finance',
    description: '世界一安全な銀行（自称）。ログアウトしても Cookie は残る。',
    cookie: {
      name: 'bank_auth',
      valueGenerator: () => `bank_${rand(16)}`,
      attributes: { secure: true, httpOnly: true, sameSite: 'Strict', maxAge: 3600 },
      points: 150,
    },
    template: 'survey',
    rarity: 'rare',
    iconEmoji: '🏦',
  },
  {
    id: 'crypto-exchange',
    name: 'CryptoExchange',
    category: 'finance',
    description: '24時間無休の仮想通貨取引所。秘密鍵は絶対に教えないでください。',
    cookie: {
      name: 'crypto_session',
      valueGenerator: () => `0x${rand(32)}`,
      attributes: { secure: true, httpOnly: true, sameSite: 'Strict', maxAge: 1800 },
      points: 130,
    },
    template: 'survey',
    rarity: 'rare',
    iconEmoji: '₿',
  },
  {
    id: 'gold-vault',
    name: 'GoldVault',
    category: 'finance',
    description: '金の延べ棒をオンラインで購入できる謎の金融サービス。',
    cookie: {
      name: 'vault_token',
      valueGenerator: () => `gv_${rand(20)}`,
      attributes: { secure: true, httpOnly: true, sameSite: 'Lax', maxAge: 7200 },
      points: 120,
    },
    template: 'survey',
    rarity: 'rare',
    iconEmoji: '🪙',
  },

  // ── ecommerce (uncommon → login-form) ────────────────────────────
  {
    id: 'shop-mart',
    name: 'ShopMart',
    category: 'ecommerce',
    description: 'なんでも売ってるショッピングモール。一度商品を見るとどこに行っても追ってくる。',
    cookie: {
      name: 'cart_id',
      valueGenerator: () => `cart_${rand(12)}`,
      attributes: { sameSite: 'Lax', maxAge: 86400 * 30 },
      points: 60,
    },
    template: 'login-form',
    rarity: 'uncommon',
    iconEmoji: '🛒',
  },
  {
    id: 'electro-store',
    name: 'ElectroStore',
    category: 'ecommerce',
    description: '最新ガジェット専門店。カートに入れた瞬間に値上がりする。',
    cookie: {
      name: 'electro_uid',
      valueGenerator: () => `eu_${rand(10)}`,
      attributes: { sameSite: 'Lax', maxAge: 86400 * 7 },
      points: 55,
    },
    template: 'login-form',
    rarity: 'uncommon',
    iconEmoji: '💻',
  },

  // ── social (uncommon → login-form) ───────────────────────────────
  {
    id: 'tweet-space',
    name: 'TweetSpace',
    category: 'social',
    description: '140文字で世界を変えようとする人々が集うSNS。',
    cookie: {
      name: 'tw_sess',
      valueGenerator: () => `twsess_${rand(24)}`,
      attributes: { secure: true, sameSite: 'Lax', maxAge: 86400 * 30 },
      points: 70,
    },
    template: 'login-form',
    rarity: 'uncommon',
    iconEmoji: '🐦',
  },
  {
    id: 'face-connect',
    name: 'FaceConnect',
    category: 'social',
    description: '顔写真を公開することへの抵抗を消し去った元祖SNS。',
    cookie: {
      name: 'fc_token',
      valueGenerator: () => `fc_${rand(20)}`,
      attributes: { secure: true, sameSite: 'Lax', maxAge: 86400 * 90 },
      points: 75,
    },
    template: 'login-form',
    rarity: 'uncommon',
    iconEmoji: '👤',
  },
  {
    id: 'photo-gram',
    name: 'PhotoGram',
    category: 'social',
    description: '盛れた写真だけ投稿するフォトシェアリングアプリ。',
    cookie: {
      name: 'pg_session',
      valueGenerator: () => `pg_${rand(18)}`,
      attributes: { secure: true, sameSite: 'Lax', maxAge: 86400 * 14 },
      points: 65,
    },
    template: 'login-form',
    rarity: 'uncommon',
    iconEmoji: '📸',
  },

  // ── media ─────────────────────────────────────────────────────────
  {
    id: 'news-portal',
    name: 'NewsPortal',
    category: 'media',
    description: '24時間速報を流し続けるニュースサイト。登録した覚えがないのにメルマガが届く。',
    cookie: {
      name: 'np_reader',
      valueGenerator: () => `np_${rand(10)}`,
      attributes: { sameSite: 'Lax', maxAge: 86400 },
      points: 40,
    },
    template: 'consent-button',
    rarity: 'common',
    iconEmoji: '📰',
  },
  {
    id: 'video-stream',
    name: 'VideoStream',
    category: 'media',
    description: '動画ストリーミングサービス。冒頭の広告が本編より長い。',
    cookie: {
      name: 'vs_auth',
      valueGenerator: () => `vs_${rand(16)}`,
      attributes: { secure: true, sameSite: 'Lax', maxAge: 86400 * 30 },
      points: 80,
    },
    template: 'login-form',
    rarity: 'uncommon',
    iconEmoji: '🎬',
  },

  // ── gaming ────────────────────────────────────────────────────────
  {
    id: 'game-zone',
    name: 'GameZone',
    category: 'gaming',
    description: '課金しないとクリアできないゲームが揃うポータル。',
    cookie: {
      name: 'gz_player',
      valueGenerator: () => `gz_${rand(14)}`,
      attributes: { sameSite: 'Lax', maxAge: 86400 * 7 },
      points: 90,
    },
    template: 'survey',
    rarity: 'uncommon',
    iconEmoji: '🎮',
  },
  {
    id: 'online-casino',
    name: 'OnlineCasino',
    category: 'gaming',
    description: '「必勝法あります」という広告が絶えないオンラインカジノ。',
    cookie: {
      name: 'casino_chip',
      valueGenerator: () => `chip_${rand(16)}`,
      attributes: { secure: true, sameSite: 'Strict', maxAge: 86400 },
      points: 110,
    },
    template: 'survey',
    rarity: 'rare',
    iconEmoji: '🎰',
  },

  // ── advertising (common → ad-popup / consent-button) ─────────────
  {
    id: 'ad-network',
    name: 'AdNetwork',
    category: 'advertising',
    description: 'あなたの行動を24時間監視して広告を最適化する会社。',
    cookie: {
      name: 'ad_uid',
      valueGenerator: () => `adn_${rand(8)}`,
      attributes: { sameSite: 'None', maxAge: 86400 * 365 },
      points: 30,
    },
    template: 'ad-popup',
    rarity: 'common',
    iconEmoji: '📢',
  },
  {
    id: 'tracker-corp',
    name: 'TrackerCorp',
    category: 'advertising',
    description: 'トラッキングピクセルを10億サイトに設置している謎の企業。',
    cookie: {
      name: 'tc_track',
      valueGenerator: () => `tc_${rand(10)}`,
      attributes: { sameSite: 'None', maxAge: 86400 * 365 * 2 },
      points: 25,
    },
    template: 'consent-button',
    rarity: 'common',
    iconEmoji: '👁️',
  },

  // ── government (uncommon → survey) ───────────────────────────────
  {
    id: 'tax-agency',
    name: 'TaxAgency',
    category: 'government',
    description: '確定申告ポータル。UIは2003年から更新されていない。',
    cookie: {
      name: 'tax_session',
      valueGenerator: () => `tax_${rand(20)}`,
      attributes: { secure: true, httpOnly: true, sameSite: 'Strict', maxAge: 1800 },
      points: 100,
    },
    template: 'survey',
    rarity: 'uncommon',
    iconEmoji: '🏛️',
  },

  // ── niche (common → consent-button) ──────────────────────────────
  {
    id: 'conspiracy-forum',
    name: 'ConspiracyForum',
    category: 'niche',
    description: 'あらゆる陰謀論を真剣に議論する掲示板。月面着陸は演出。',
    cookie: {
      name: 'cf_anon',
      valueGenerator: () => `cf_${rand(8)}`,
      attributes: { sameSite: 'Lax', maxAge: 86400 * 365 },
      points: 35,
    },
    template: 'consent-button',
    rarity: 'common',
    iconEmoji: '👽',
  },
  {
    id: 'ghost-hunter',
    name: 'GhostHunter',
    category: 'niche',
    description: '全国の心霊スポット情報を集めたサイト。管理人は連絡不通。',
    cookie: {
      name: 'ghost_trace',
      valueGenerator: () => `gh_${rand(10)}`,
      attributes: { sameSite: 'Lax', maxAge: 86400 * 13 },
      points: 45,
    },
    template: 'consent-button',
    rarity: 'common',
    iconEmoji: '👻',
  },

  // ── social (追加) ────────────────────────────────────────────────
  {
    id: 'video-tube',
    name: 'VideoTube',
    category: 'social',
    description: '動画を見ながらいつの間にか3時間経っている動画プラットフォーム。',
    cookie: {
      name: 'vt_session',
      valueGenerator: () => `vt_${rand(18)}`,
      attributes: { secure: true, sameSite: 'Lax', maxAge: 86400 * 30 },
      points: 70,
    },
    template: 'consent-button',
    rarity: 'uncommon',
    iconEmoji: '📺',
  },
  {
    id: 'short-clip',
    name: 'ShortClip',
    category: 'social',
    description: '15秒で世界が変わるショート動画アプリ。踊れる人が有利。',
    cookie: {
      name: 'sc_uid',
      valueGenerator: () => `sc_${rand(14)}`,
      attributes: { sameSite: 'Lax', maxAge: 86400 * 60 },
      points: 55,
    },
    template: 'consent-button',
    rarity: 'common',
    iconEmoji: '🎵',
  },
  {
    id: 'pro-network',
    name: 'ProNetwork',
    category: 'social',
    description: 'ビジネス人脈を「つながり」で広げるSNS。上司の投稿にいいねするのが暗黙のルール。',
    cookie: {
      name: 'pn_auth',
      valueGenerator: () => `pn_${rand(20)}`,
      attributes: { secure: true, sameSite: 'Lax', maxAge: 86400 * 30 },
      points: 82,
    },
    template: 'survey',
    rarity: 'uncommon',
    iconEmoji: '💼',
  },

  // ── finance (追加) ────────────────────────────────────────────────
  {
    id: 'pay-ez',
    name: 'PayEZ',
    category: 'finance',
    description: 'QRコードをかざすだけで決済完了。残高が気づかず減る魔法のアプリ。',
    cookie: {
      name: 'pez_token',
      valueGenerator: () => `pez_${rand(16)}`,
      attributes: { secure: true, httpOnly: true, sameSite: 'Strict', maxAge: 3600 },
      points: 48,
    },
    template: 'consent-button',
    rarity: 'common',
    iconEmoji: '💳',
  },
  {
    id: 'stock-ticker',
    name: 'StockTicker',
    category: 'finance',
    description: 'AIによる相場予測を売りにした投資プラットフォーム。的中率は天気予報レベル。',
    cookie: {
      name: 'st_investor',
      valueGenerator: () => `sti_${rand(22)}`,
      attributes: { secure: true, httpOnly: true, sameSite: 'Strict', maxAge: 7200 },
      points: 132,
    },
    template: 'survey',
    rarity: 'rare',
    iconEmoji: '📈',
  },
  {
    id: 'loan-easy',
    name: 'LoanEasy',
    category: 'finance',
    description: '審査なし・即日融資。実質年利は注釈の注釈に小さく書いてある。',
    cookie: {
      name: 'loan_sess',
      valueGenerator: () => `le_${rand(18)}`,
      attributes: { secure: true, httpOnly: true, sameSite: 'Strict', maxAge: 1800 },
      points: 92,
    },
    template: 'survey',
    rarity: 'uncommon',
    iconEmoji: '💰',
  },

  // ── gaming (追加) ────────────────────────────────────────────────
  {
    id: 'live-cast',
    name: 'LiveCast',
    category: 'gaming',
    description: 'ゲーム配信者と視聴者が盛り上がるライブ配信プラットフォーム。投げ銭が止まらない。',
    cookie: {
      name: 'lc_viewer',
      valueGenerator: () => `lc_${rand(16)}`,
      attributes: { sameSite: 'Lax', maxAge: 86400 * 7 },
      points: 85,
    },
    template: 'consent-button',
    rarity: 'uncommon',
    iconEmoji: '🎥',
  },
  {
    id: 'retro-arcade',
    name: 'RetroArcade',
    category: 'gaming',
    description: '80年代の名作ゲームが遊べるアーカイブ。会員登録時にセキュリティ知識を問われる。',
    cookie: {
      name: 'retro_pass',
      valueGenerator: () => `ra_${rand(20)}`,
      attributes: { secure: true, httpOnly: true, sameSite: 'Strict', maxAge: 86400 },
      points: 155,
    },
    template: 'quiz',
    rarity: 'rare',
    iconEmoji: '🕹️',
  },
  {
    id: 'esports-hub',
    name: 'EsportsHub',
    category: 'gaming',
    description: 'プロゲーマーの試合結果が集まるeスポーツポータル。回線の良さが実力の半分。',
    cookie: {
      name: 'eh_profile',
      valueGenerator: () => `eh_${rand(14)}`,
      attributes: { sameSite: 'Lax', maxAge: 86400 * 14 },
      points: 78,
    },
    template: 'survey',
    rarity: 'uncommon',
    iconEmoji: '🏆',
  },

  // ── niche (追加) ──────────────────────────────────────────────────
  {
    id: 'astro-scope',
    name: 'AstroScope',
    category: 'niche',
    description: '今日の運勢を星の配置で導く占いサイト。当たる確率は理論上50%。',
    cookie: {
      name: 'astro_sign',
      valueGenerator: () => `as_${rand(10)}`,
      attributes: { sameSite: 'Lax', maxAge: 86400 },
      points: 40,
    },
    template: 'consent-button',
    rarity: 'common',
    iconEmoji: '⭐',
  },
  {
    id: 'recipe-share',
    name: 'RecipeShare',
    category: 'niche',
    description: '主婦（主夫）が集うレシピ共有サイト。コメント欄は予想外の激戦区。',
    cookie: {
      name: 'rs_user',
      valueGenerator: () => `rs_${rand(10)}`,
      attributes: { sameSite: 'Lax', maxAge: 86400 * 30 },
      points: 33,
    },
    template: 'consent-button',
    rarity: 'common',
    iconEmoji: '🍳',
  },

  // ── F12確認用サイト ───────────────────────────────────────────────
  {
    id: 'dev-tools-lab',
    name: 'DevToolsLab',
    category: 'special',
    description: 'Cookieの中身を隠さない開発者向けサイト。HttpOnly属性なしの「丸見え」Cookieを発行する。',
    cookie: {
      name: 'devlab_visible',
      valueGenerator: () => `VISIBLE_${rand(16).toUpperCase()}`,
      attributes: { sameSite: 'Lax', maxAge: 86400 },
      points: 60,
    },
    template: 'consent-button',
    rarity: 'uncommon',
    iconEmoji: '🔧',
  },

  // ── honeypot (ad-popup, negative points) ─────────────────────────
  {
    id: 'secuure-bank',
    name: 'SecuureBank',
    category: 'honeypot',
    description: '銀行っぽいサイト。よく見ると "u" が2つある…',
    cookie: {
      name: 'phish_trap',
      valueGenerator: () => `trap_${rand(8)}`,
      attributes: { sameSite: 'Lax', maxAge: 60 },
      points: -50,
    },
    template: 'ad-popup',
    rarity: 'common',
    isHoneypot: true,
    iconEmoji: '🏦',
  },
  {
    id: 'add-network',
    name: 'AddNetwork',
    category: 'honeypot',
    description: 'AdNetworkに似た名前の怪しいサイト。d が2つある。',
    cookie: {
      name: 'malware_id',
      valueGenerator: () => `mal_${rand(6)}`,
      attributes: { maxAge: 86400 * 365 },
      points: -30,
    },
    template: 'ad-popup',
    rarity: 'common',
    isHoneypot: true,
    iconEmoji: '📢',
  },

  // ── mystery (shown as ??? until visited) ─────────────────────────
  {
    id: 'mystery-alpha',
    name: 'MysteryBox',
    category: 'niche',
    description: '中身がわからない箱を売っているらしいサイト。何が届くかは開けてからのお楽しみ。',
    cookie: {
      name: 'mystery_alpha',
      valueGenerator: () => `mx_${rand(12)}`,
      attributes: { sameSite: 'Lax', maxAge: 86400 },
      points: 50,
    },
    template: 'consent-button',
    rarity: 'common',
    iconEmoji: '❓',
    isMystery: true,
  },
  {
    id: 'mystery-beta',
    name: 'CryptoMail',
    category: 'special',
    description: 'エンドツーエンド暗号化を謳うメールサービス。大学のメールアドレスで登録するとCookieを取得する。',
    cookie: {
      name: 'mystery_beta',
      valueGenerator: () => `mb_${rand(16)}`,
      attributes: { secure: true, sameSite: 'Strict', maxAge: 3600 },
      points: 85,
    },
    template: 'login-form',
    rarity: 'uncommon',
    iconEmoji: '🔐',
    isMystery: true,
  },
  {
    id: 'mystery-gamma',
    name: 'PrizeWinner',
    category: 'honeypot',
    description: '派手なポップアップで「あなたが選ばれました」と表示するサイト。受け取るボタンが画面を埋め尽くす。',
    cookie: {
      name: 'mystery_gamma',
      valueGenerator: () => `mg_${rand(8)}`,
      attributes: { maxAge: 60 },
      points: -40,
    },
    template: 'ad-popup',
    rarity: 'common',
    iconEmoji: '💀',
    isHoneypot: true,
    isMystery: true,
  },
  {
    id: 'mystery-delta',
    name: 'SecurityLab',
    category: 'special',
    description: '研究機関を名乗るサイト。セキュリティ意識調査に答えるとCookieを取得する。',
    cookie: {
      name: 'mystery_delta',
      valueGenerator: () => `md_${rand(14)}`,
      attributes: { httpOnly: true, sameSite: 'Strict', maxAge: 7200 },
      points: 110,
    },
    template: 'survey',
    rarity: 'rare',
    iconEmoji: '🔬',
    isMystery: true,
  },
  {
    id: 'mystery-omega',
    name: 'CyberLegend',
    category: 'special',
    description: 'ネットの都市伝説サイト。難解なクイズに全問正解できた者だけCookieを取得する。',
    cookie: {
      name: 'mystery_omega',
      valueGenerator: () => `mo_${rand(20)}`,
      attributes: { secure: true, httpOnly: true, sameSite: 'Strict', maxAge: 86400 * 30 },
      points: 170,
    },
    template: 'quiz',
    rarity: 'legendary',
    iconEmoji: '🌀',
    isMystery: true,
  },

  // ── special (legendary → quiz) ────────────────────────────────────
  {
    id: 'ghost-site',
    name: 'GhostSite',
    category: 'special',
    description: 'Max-Age=10秒のCookieを発行する。取得しても10秒で消える。ゲーム終盤に取れば実質持ち越せる。',
    cookie: {
      name: 'ghost_cookie',
      valueGenerator: () => `👻${rand(12)}`,
      attributes: { sameSite: 'Lax', maxAge: 10 },
      points: 200,
    },
    template: 'quiz',
    rarity: 'legendary',
    iconEmoji: '👾',
  },
  {
    id: 'eternal-session',
    name: 'EternalSession',
    category: 'special',
    description: '100年有効なCookieを発行するサービス。孫の代まで追跡される。',
    cookie: {
      name: 'eternal_id',
      valueGenerator: () => `eternity_${rand(20)}`,
      attributes: { secure: true, sameSite: 'None', maxAge: 86400 * 365 * 100 },
      points: 180,
    },
    template: 'quiz',
    rarity: 'legendary',
    iconEmoji: '♾️',
  },
];

export function getSiteById(id: string): Site | undefined {
  return SITES.find(s => s.id === id);
}

export const CATEGORY_LABELS: Record<string, string> = {
  finance: '金融',
  ecommerce: 'EC',
  social: 'SNS',
  media: 'メディア',
  gaming: 'ゲーム',
  advertising: '広告',
  government: '政府',
  niche: 'ニッチ',
  honeypot: '罠',
  special: '特殊',
};
