# === v11: 空ラベル許容preproc（純静穏クリップ対応） ===============================
# 設計= md/design/v11データセット拡張_設計書_2026-07-27.md §1.5（実証済み）。
# v11 coreは「純静穏」582本（音源ゼロ→ラベルCSVが0バイト）を学習の教師として
# **意図的に**含む。素のPSELDNets preprocは空CSVで EmptyDataError で停止するため、
# pin済みsubmodule本体には触れず、読み込み2関数をラップした別プロセスでpreprocを回す。
#
# パッチ設計の要点（例外catch方式にしない理由）:
#   pd.read_csv を例外フォールバックでラップすると load_output_format_file 内部の
#   read_csv も番兵行を受け取って「frame99にクラス0のイベント」を偽生成してしまう
#   （2026-07-27精査で発見した合成事故）。**0バイト判定**なら順序に依存しない:
#   - load_output_format_file: 空 → {99: []}（イベント0件・最終フレームのみ）
#   - pd.read_csv:             空 → 番兵行（num_frames=100の算出専用。イベント抽出
#                                     には使われない——上のload側が先に空を処理する）
# 従来の「空ラベル除外セル」はv11では**使わない**（偶発的な完全不可聴クリップも
# 正当な負例として学習に残す=設計と整合）。
import os
import subprocess
import sys
from pathlib import Path

DATASET = "outdoor_siren_v11"

WRAPPER = r'''# _preproc_emptyok.py (auto-generated by cell_v11_preproc_emptyok)
import os
import runpy
import sys

sys.path.insert(0, "src")
import pandas as pd
import utils.data_utilities as du
import preproc.preprocess as pp

_load, _read = du.load_output_format_file, pd.read_csv


def _is_empty_file(path):
    try:
        return os.path.getsize(path) == 0
    except (TypeError, OSError, ValueError):
        return False


def load_ok(path, *a, **kw):
    if _is_empty_file(path):
        return {99: []}          # 最終フレームのみ・イベント0件（ゼロ行列になる）
    return _load(path, *a, **kw)


def read_ok(path, *a, **kw):
    if _is_empty_file(path):
        return pd.DataFrame([[99, 0, 0, 0, 0]])   # num_frames=100 算出専用の番兵
    return _read(path, *a, **kw)


du.load_output_format_file = load_ok
pp.load_output_format_file = load_ok   # preprocessはfrom-importなので名前ごと差し替え
pd.read_csv = read_ok                  # 別プロセス内のみのグローバル差し替え

sys.argv = ["src/preproc.py"] + sys.argv[1:]
runpy.run_path("src/preproc.py", run_name="__main__")
'''

IDX = f"_hdf5/data/24000fs/wav/dev/{DATASET}_10sChunklen_10sHoplen_train.csv"
if os.path.exists(IDX):
    print("前処理済み:", IDX)
else:
    Path("_preproc_emptyok.py").write_text(WRAPPER, encoding="utf-8")
    subprocess.run([sys.executable, "_preproc_emptyok.py", f"dataset={DATASET}"],
                   check=True)
    print("preproc done (empty-label tolerant)")
# 検算: 空ラベルクリップがindexに残っていること（除外されていたら設計違反）
import pandas as _pd  # noqa: E402
_idx = _pd.read_csv(IDX, header=None)
print("index rows:", len(_idx))
